language: java
jdk:
  - oraclejdk8
script: mvn test -e -Dhdf5lib-absolute-path=`pwd`/lib/linux64 --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true
#-Dmaven.test.redirectTestOutputToFile
env:
  global:
    - export MAVEN_OPTS="-Xmx2500m"


